
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
    env: dev
spec:
  selector:
      matchLabels:
        app: console
        env: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: console
        env: dev
    spec:
      containers:
      - name: console
        image: feynlabdevacr.azurecr.io/console:placeholdertag
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dev-regcred