apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    app: console
    env: dev
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 3000
  selector:
    app: console
    env: dev